# Generated by Django 2.0 on 2018-10-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='modified',
            new_name='modifiedDate',
        ),
    ]
