# Generated by Django 2.0 on 2018-10-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_auto_20181024_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('deletedAtDate', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
