# Generated by Django 2.0 on 2018-10-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
