# Generated by Django 2.0 on 2018-10-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_auto_20181024_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
