# Generated by Django 2.0 on 2018-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0006_auto_20181027_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alert_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='alert_time',
            field=models.DateTimeField(null=True),
        ),
    ]
