# Generated by Django 2.0 on 2018-11-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0007_auto_20181029_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='deletedAtDate',
            new_name='deleted_at_date',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deletedAtDate',
            new_name='deleted_at_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
    ]
